cutoff_len: 512
dataset: aclarc
dataset_dir: data
ddp_timeout: 180000000
deepspeed: cache/ds_z3_offload_config.json
do_train: true
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 1
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 10
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 1688
model_name_or_path: Qwen/Qwen2.5-14B-Instruct
num_train_epochs: 10.0
optim: adamw_torch
output_dir: saves/Qwen2.5-14B-Instruct/lora/train_2025-02-10_aclarc-alpaca_config4
packing: false
per_device_train_batch_size: 16
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: qwen
trust_remote_code: true
warmup_steps: 500
